---
- name: "Getting latest version for {{ get_binary_cmd }}"
  tags:
    - install
  block:
    - name: "Gettting latest version for {{ get_binary_cmd }}"
      ansible.builtin.uri:
        url: "{{ get_binary_url_latest }}"
      register: get_version_latest_result

    - name: "Print results"
      ansible.builtin.debug:
        var: get_version_latest_result.json.tag_name[0]
    - name: "Removing 'v' from version"
      ansible.builtin.set_fact:
        get_binary_version_latest: "{{ get_version_latest_result.json.tag_name[1:] }}"
    - name: "Print results"
      ansible.builtin.debug:
        var: get_binary_version_latest
    # - pause:
