---
- name: "Install cosign binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "cosign"
    get_binary_version: "{{ cosign_version }}"
    get_binary_url: "https://github.com/sigstore/cosign/releases/download/v{{ get_binary_version }}/cosign-{{ my_os }}-{{ my_arch }}"
    get_binary_version_subcmd: "version"
    get_binary_post_version_args: "| grep GitVersion"
    get_binary_parse_delimeter: "v"
    get_binary_parse_index: 1
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
