---
- name: "Install flux binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "flux"
    get_binary_version: "{{ flux_version }}"
    get_binary_url: "https://github.com/fluxcd/flux2/releases/download/v{{ get_binary_version }}/flux_{{ get_binary_version }}_{{ my_os }}_{{ my_arch }}.tar.gz"
    get_binary_version_subcmd: "--version"
    get_binary_parse_delimeter: " "
    get_binary_parse_index: 2
    get_binary_extract: true
    get_binary_extract_exclude: []
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
