---
- name: "Install kopia"
  tags:
    - clean
    - install
    - verify
  block:
    - name: "Set default os to 'my_os_final'"
      ansible.builtin.set_fact:
        my_os_final: "{{ my_os }}"
        my_arch_final: "{{ my_arch }}"
        my_extension: "tar.gz"
        get_binary_extra_opts:
          - --strip=1
          - --wildcards
          - "*/kopia"

    - name: "Handle linux correctly"
      when: my_arch == "amd64"
      ansible.builtin.set_fact:
        my_arch_final: "x64"

    - name: "Handle macos correctly"
      when: my_os == "darwin"
      ansible.builtin.set_fact:
        my_os_final: "macOS"

    - name: "Install kopia binary"
      ansible.builtin.include_role:
        name: get_binary
      vars:
        get_binary_cmd: "kopia"
        get_binary_version: "{{ kopia_version }}"
        get_binary_version_subcmd: "--version"
        get_binary_url: >
          https://github.com/kopia/kopia/releases/download/v{{ get_binary_version }}/kopia-{{ get_binary_version }}-{{ my_os_final }}-{{ my_arch_final }}.tar.gz
        get_binary_parse_delimeter: " "
        get_binary_parse_index: 0
        get_binary_extract: true
        get_binary_extract_exclude: ["LICENCE", "README.md"]
        get_binary_version_rcs: [0, 1]
