---
- name: "Install kubeseal binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "kubeseal"
    get_binary_version: "{{ kubeseal_version }}"
    get_binary_version_subcmd: "--version"
    get_binary_url: >
      https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{ get_binary_version }}/kubeseal-{{ get_binary_version }}-{{ my_os }}-{{ my_arch }}.tar.gz
    get_binary_parse_delimeter: " "
    get_binary_parse_index: 2
    get_binary_extract: true
    get_binary_extract_exclude: ["LICENCE", "README.md"]
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
