---
- name: "Install lazygit binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "lazygit"
    get_binary_version: "{{ lazygit_version }}"
    get_binary_version_subcmd: "--version"
    get_binary_url: >
      https://github.com/jesseduffield/lazygit/releases/download/v{{ get_binary_version }}/lazygit_{{ get_binary_version }}_{{ my_os }}_x86_64.tar.gz
    get_binary_post_version_args: "| cut -d '=' -f 5"
    get_binary_parse_delimeter: ","
    get_binary_parse_index: 0
    get_binary_extract: true
    get_binary_extract_exclude: []
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
