---
- name: "Install medusa binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "medusa"
    get_binary_version: "{{ medusa_version }}"
    get_binary_url: "https://github.com/jonasvinther/medusa/releases/download/v{{ get_binary_version }}/medusa_{{ get_binary_version }}_{{ my_os }}_{{ my_arch }}.tar.gz"
    get_binary_post_version_args: ' | cut -d ''"'' -f1'
    get_binary_parse_delimeter: "v"
    get_binary_parse_index: 1
    get_binary_extract: true
    get_binary_extract_exclude: ["LICENCE", "README.md"]
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
