---
- name: "Install oc binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "oc"
    get_binary_version: "{{ oc_version }}"
    get_binary_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ get_binary_version }}/openshift-client-{{ my_os }}-{{ get_binary_version }}.tar.gz"
    get_binary_parse_delimeter: " "
    get_binary_parse_index: 2
    get_binary_extract: true
    get_binary_extract_exclude: ["kubectl", "README.md"]
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
