---
- name: "Install tkn binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "tkn"
    get_binary_version: "{{ tkn_version }}"
    get_binary_url: "https://github.com/tektoncd/cli/releases/download/v{{ get_binary_version }}/tkn_{{ get_binary_version }}_{{ my_os }}_x86_64.tar.gz"
    get_binary_parse_delimeter: " "
    get_binary_parse_index: 2
    get_binary_extract: true
    get_binary_extract_exclude: ["LICENSE", "README.md"]
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
