---
- name: "Install vault binary"
  ansible.builtin.include_role:
    name: get_binary
  vars:
    get_binary_cmd: "vault"
    get_binary_version: "{{ vault_version }}"
    get_binary_url: "https://releases.hashicorp.com/vault/{{ get_binary_version[1:] }}/vault_{{ get_binary_version[1:] }}_{{ my_os }}_{{ my_arch }}.zip"
    get_binary_parse_delimeter: " "
    get_binary_parse_index: 1
    get_binary_extract: true
    get_binary_extract_exclude: ["LICENSE.txt"]
    get_binary_version_rcs: [0, 1]
  tags:
    - clean
    - install
    - verify
