---
- name: "Uninstall velero"
  ansible.builtin.command: "{{ velero_binary }} uninstall --force"
  changed_when: true
  failed_when: false
  tags:
    - clean

- name: "Installing velero"
  tags:
    - install
    - restore
  block:
    - name: "Generate velero aws secret file"
      ansible.builtin.template:
        src: velero-aws-credential.j2
        dest: "{{ velero_secret_file_path }}"
        mode: "0644"

    - name: "Installing velero"
      ansible.builtin.command: >
        {{ velero_binary }} install
        --plugins velero/velero-plugin-for-aws:{{ velero_plugin_for_aws_version }}
        --use-node-agent
        --features=EnableCSI
        --use-volume-snapshots=false
        --secret-file={{ velero_secret_file_path }}
        --bucket {{ velero_bucket_name }}
        --provider {{ velero_provider }}
        --backup-location-config region={{ velero_bucket_aws_region }}
        {{ velero_storage_location_name }}
      changed_when: true

- name: "Restore backups"
  tags:
    - restore
  block:
    - name: "Set velero namespace list"
      ansible.builtin.set_fact:
        velero_namespace_list: "{{ velero_namespaces.split(',') | list }}"
      when:
        - velero_namespaces is defined
        - velero_namespaces|length > 0

    - name: "Restoring namespace {{ namespace_item }}"
      ansible.builtin.include_tasks:
        file: "restore.yml"
      loop: "{{ velero_namespace_list }}"
      loop_control:
        loop_var: namespace_item
